### ISSUE TITLE
Add CI GIthub Workflow

### ISSUE THREAD

**Issue by Alitindrawan24** [idna001/Couple-Memory#20]
Adding CI GIthub Workflow will be useful to make every new PR into main branch can be run build and test script successfully
Can I work on this?

**Comment by idna001** [comment]
Hay, 
Sure, you can add a Workflow. 
But please only if it's no duplicate. There are already a deployment and test workflow. 
![grafik](https://github.com/idna001/Couple-Memory/assets/46223359/322109cb-a97d-4b66-885a-fe0b10fe25ce)

Thanks for your Issue

**Comment by Alitindrawan24** [comment]
I see, I think the GitHub workflow will be similar to the existing one. So I will close this issue, Thank you

**Comment by idna001** [comment]
@Alitindrawan24 No Problem, enjoy Hacktober!
