### ISSUE TITLE
 Animation on Pictures if they match

### ISSUE THREAD

**Issue by idna001** [idna001/Couple-Memory#22]

**Comment by mohiwalla** [comment]
Hi @idna001 I think you need to provide a description for this issue. How can someone that what are you talking about from this empty description?

**Comment by idna001** [comment]
@mohiwalla 
Yes, okay, I did not want to limit the editor. 
With this is meant, if you play the memory and make a match, you get a sound as confirmation and the pictures will not turn over anymore. 

I would additionally like an animation like a short highlighting by double blinking or by a short shadow behind the two pictures. 

Or maybe like a firework, which is created at the pictures. 

Here you can get creative and pick a highlighting that you like.

Translated with www.DeepL.com/Translator (free version)

**Comment by mohiwalla** [comment]
Got it.! Would you first assign this issue to me OR shall I directly raise a PR?

**Comment by idna001** [comment]
How is it going? :)

**Comment by mohiwalla** [comment]
Oh yes I managed to do it, but forgot to push. 🙂

**Comment by mohiwalla** [comment]
Sorry for the delay, just made a `pull request`, please review do we need any further changes...

**Comment by idna001** [comment]
@mohiwalla No Problem, Thank you
