### ISSUE TITLE
Button, that makes a Screenshot of the Highscore to share it with friends

### ISSUE THREAD

**Issue by idna001** [idna001/Couple-Memory#24]
Only if new Highscore is achieved.

**Comment by insane-22** [comment]
Hey @idna001 ! I would like to contribute to your project under hacktoberfest 2023,
Kindly assign this issue to me.
Changes I plan to make:- using html2canvas library to take screenshot and save it, adding share the screenshot through different social media links.
Your feedback would be highly appreciated,
Thank you for your consideration!

**Comment by idna001** [comment]
@insane-22 Hay, thanks for your comment. 
html2canvas seems to be a good option. 
Please make sure it's also working on Mobile Viewport. 

Appreciate the commitment 
Enjoy Hacktoberfest!

**Comment by insane-22** [comment]
Hello @idna001,
Thank you for assigning this issue to me.
Video link after changes:-
[Screencast from 05-10-23 07:20:11 PM IST.webm](https://github.com/idna001/Couple-Memory/assets/116253210/30c8e674-6781-46f5-852d-46f744777932)
Is it ok or should I make any changes?

**Comment by idna001** [comment]
Hey, @insane-22 
For the first step, this is totally fine. Maybe it also would be great to see in the Screenshot the Headline of the Game. 
And on the next step, calling the web share API would be awesome. 
Here is an example: https://codepen.io/ayoisaiah/pen/YbNazJ
https://css-tricks.com/how-to-use-the-web-share-api/ 

Then you get a lot of personal sharing options in the best case.

But this is also fine, just share a Pull Request and I will test it and look up the code. 

Thanks for your very fast change!
