### ISSUE TITLE
Add runtime in Local Storage and show with High score

### ISSUE THREAD

**Issue by idna001** [idna001/Couple-Memory#40]
Add time next to high score
![grafik](https://github.com/idna001/Couple-Memory/assets/46223359/53fcedb1-44c9-430b-b59d-283097546c8e)

So it will be possible to achieve a new high score with the same amount of turns, but with a faster time.

**Comment by Pinaka-Pani-18** [comment]
Hi, Can I work on this issue ?

**Comment by idna001** [comment]
@Pinaka-Pani-18 Sure, go for it

**Comment by barkha-gupta** [comment]
Hii @idna001, I would like to work on the issue. 
I tried solving. Are you looking for something like this: 

![Screenshot 2023-10-19 141718](https://github.com/idna001/Couple-Memory/assets/114416337/37adcae6-3542-464b-ba77-453acb9d48be)

**Comment by idna001** [comment]
@barkha-gupta 
Yes, exactly, but with the logic to achieve the high score with the same turns and less runtime.
Just raise a PR and I will take a look. 

Thank you, for your contribution!

**Comment by barkha-gupta** [comment]
I have made the PR. Please let me know if the logic is fine or any more changes that need to be done. Thanks.
