### ISSUE TITLE
Fix: one of the images is not present in public/img 

### ISSUE THREAD

**Issue by barkha-gupta** [idna001/Couple-Memory#62]
**Problem**
* One of the images in the cardImages array is not present in the img folder in public. 
* its causing one of the cards being empty

![Screenshot 2023-10-21 151713](https://github.com/idna001/Couple-Memory/assets/114416337/c82d9166-dc84-4cdd-8f9d-97caf7e730ff)

**Comment by barkha-gupta** [comment]
i can remove the source of image from cardImages array.

**Comment by idna001** [comment]
Ah thanks for noticing, this came up from this #18 from a few days ago
You can fix this if you like
