### ISSUE TITLE
BUG: Elapsed Timer Keeps on going even after game finishes

### ISSUE THREAD

**Issue by abhisheksharm-3** [idna001/Couple-Memory#64]
- This Bug affects the final screenshot user takes and thus providing inaccurate timestamps
- I can try to fix the issue by either fixing current logic or rewriting the logic to correct it

**Comment by idna001** [comment]
Thanks for reporting this issue, this was already an Issue that somehow is back again. 
Maybe you can look up the changed files. 
https://github.com/idna001/Couple-Memory/issues/48

**Comment by abhisheksharm-3** [comment]
Hey @idna001 , i think I've fixed the issue, will test it once more and push it by tomorrow.
