### ISSUE TITLE
Picture dimensions CSS fix

### ISSUE THREAD

**Issue by idna001** [idna001/Couple-Memory#77]

**Comment by KinshukK15** [comment]
Can you please elaborate on the issue?

**Comment by idna001** [comment]
@KinshukK15 
Sorry planned on doing it myself. But you can try it for sure. 
I always had portrait pictures, but now I switched to landscape pictures and on mobile the dimensions are wrong. 
Here is a screenshot: 
![IMG_2877](https://github.com/idna001/Couple-Memory/assets/46223359/f8a77499-26b7-4351-9a86-22a10fbbd4cf)
Feel free to make a PR, it should be a little change

**Comment by ash413** [comment]
hi i can fix it, kindly assign this issue to me!
